### ISSUE TITLE
add me in the game!!! 😡😡😡

### ISSUE THREAD

**Issue by TheBeeThat** [Aubarino/AbyssalDiscoveries#2]
NOW. DO. IT.
😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡🔞😡😡😡😡😡😭😭😭
@Aubarino

**Comment by TheBeeThat** [comment]
this is me: https://www.google.com/search?q=troll+face

**Comment by Navi-0** [comment]
no
